apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simple-app
  namespace: openshift-gitops
spec:
  destination:
    name: ''
    namespace: simple-app
    server: 'https://kubernetes.default.svc'
  source:
    path: simple-app-gitops/deploy
    repoURL:  https://github.com/charles-bate/simple-app.git
    targetRevision: HEAD
    directory:
      recurse: true
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true